modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []    # Accept all 2xxâ€“3xx
      method: GET

  http_post_200:
    prober: http
    timeout: 5s
    http:
      method: POST
      valid_status_codes: [200]

  tcp_connect:
    prober: tcp
    timeout: 5s

  icmp:
    prober: icmp
    timeout: 5s

  dns:
    prober: dns
    timeout: 4s
    dns:
      query_name: "google.com"
