services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - /opt/monitoring/otel-collector/otel-collector.yml:/etc/otel-collector.yml:ro
    ports:
      - "8888:8888"   # OTEL internal metrics
    networks:
      - monitor-net
    restart: unless-stopped

networks:
  monitor-net:
    external: true
