services:
  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: jaeger
    ports:
      - "16686:16686"
    restart: unless-stopped

  otel-gateway:
    image: otel/opentelemetry-collector-contrib:0.96.0
    container_name: otel-gateway
    command: ["--config=/etc/otel/otel-gateway.yml"]
    volumes:
      - ../config/otel-gateway.yml:/etc/otel/otel-gateway.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
    restart: unless-stopped
